// Mock API — reads static fixtures from /mock/*.json (generated by
// scripts/gen_mock_data.py) and overlays an in-memory leak simulation so the
// whole demo flow works without a backend.
import type {
  Api,
  AttentionItem,
  HouseState,
  ScoreWord,
  SensorDetail,
  SensorSeries,
} from './types'

const LEAK_TARGET_DEFAULT = 'rht-18796' // green roof leak sensor
const ALERT_AFTER_S = 45 // watch -> alert transition
const SCORE_DROP_S = 150 // score falls 84 -> 52 over this span

let sim: { startedAt: number; targetId: string } | null = null

async function mockFetch<T>(path: string): Promise<T> {
  const r = await fetch(`/mock/${path}.json`)
  if (!r.ok) throw new Error(`mock ${r.status}: ${path}`)
  return r.json() as Promise<T>
}

function elapsedS(): number {
  return sim ? (Date.now() - sim.startedAt) / 1000 : 0
}

function scoreWord(score: number): ScoreWord {
  return score >= 75 ? 'Good' : score >= 60 ? 'Fair' : 'Attention'
}

function applySim(h: HouseState): HouseState {
  if (!sim) return { ...h, simulating: false }
  const t = elapsedS()
  const severity = t >= ALERT_AFTER_S ? 'alert' : 'watch'
  const score = Math.max(
    52,
    Math.round(h.score - (h.score - 52) * Math.min(1, t / SCORE_DROP_S)),
  )
  const target = h.sensors.find((s) => s.id === sim!.targetId)
  const where = target?.name.split('·')[0].trim() ?? 'a sensor'
  const attention: AttentionItem[] = [
    {
      sensor_id: sim.targetId,
      severity,
      message:
        severity === 'alert'
          ? `Humidity at ${where.toLowerCase()} has risen sharply — this pattern usually means a leak. We've flagged it for review.`
          : `Humidity at ${where.toLowerCase()} is rising slowly. We're watching it — no action needed yet.`,
      since: new Date(sim.startedAt).toISOString(),
    },
  ]
  return {
    ...h,
    score,
    score_word: scoreWord(score),
    score_trend: 'declining',
    summary:
      severity === 'alert'
        ? 'We found a likely leak on the green roof. Everything else looks normal.'
        : 'One area needs watching — the rest of the house looks normal.',
    attention,
    sensors: h.sensors.map((s) =>
      s.id === sim!.targetId ? { ...s, status: severity } : s,
    ),
    simulating: true,
  }
}

export const mock: Api = {
  async getHouseState() {
    return applySim(await mockFetch<HouseState>('house'))
  },

  async getSensor(id) {
    const d = await mockFetch<SensorDetail>(`sensors/${id}`)
    if (!sim || id !== sim.targetId) return d
    const severity = elapsedS() >= ALERT_AFTER_S ? 'alert' : 'watch'
    return {
      ...d,
      status: severity,
      status_text:
        severity === 'alert'
          ? 'Humidity has risen sharply here in the last hour — this pattern usually means a new leak.'
          : "Humidity here is rising slowly. We're watching it — no action needed yet.",
    }
  },

  async getSeries(id, range) {
    const s = await mockFetch<SensorSeries>(`series/${id}-${range}`)
    if (!sim || id !== sim.targetId || range !== '24h') return s
    // Ramp the tail of the 24 h series so the fresh leak is visible.
    const t = Math.min(1, elapsedS() / 240)
    const n = Math.min(24, s.points.length)
    const points = s.points.map((p, i) => {
      const k = (i - (s.points.length - n)) / n
      if (k < 0 || p.rh_pct == null) return p
      return { ...p, rh_pct: p.rh_pct + (92 - p.rh_pct) * t * k }
    })
    return { ...s, points }
  },

  async simulateLeak(sensorId) {
    sim = { startedAt: Date.now(), targetId: sensorId ?? LEAK_TARGET_DEFAULT }
  },

  async resetDemo() {
    sim = null
  },
}
