// Mock API — reads static fixtures from /mock/*.json (generated by
// scripts/gen_mock_data.py) and overlays an in-memory leak simulation so the
// whole demo flow works without a backend. Fixture timestamps are shifted so
// the latest reading is always a few minutes old: the demo reads as live
// whenever it is recorded.
import type {
  Api,
  AttentionItem,
  HelpKind,
  HelpRequest,
  HouseSensor,
  HouseState,
  Report,
  ScoreWord,
  SensorDetail,
  SensorLatest,
  SensorSeries,
  Severity,
} from './types'

const LEAK_TARGET_DEFAULT = 'roof-nw' // north slope — where moisture collects
const ALERT_AFTER_S = 45 // watch -> alert transition
const SCORE_DROP_S = 150 // score falls to 52 over this span
const RH_RAMP_S = 240 // leak humidity climbs to LEAK_RH over this span
const LEAK_RH = 92
const LAST_CHECK_AGO_MS = 12 * 60_000

const HELP_CONFIRMATION: Record<HelpKind, string> = {
  inspection:
    'Inspection requested. A local VILPE-certified inspector will call you within one working day.',
  expert:
    "Sent to a VILPE expert. You'll get their assessment of the readings within 24 hours.",
}

const HELP_STATUS: Record<HelpKind, string> = {
  inspection: 'Inspector calls within 1 working day',
  expert: 'Reply within 24 hours',
}

let sim: { startedAt: number; targetId: string } | null = null
let requests: HelpRequest[] = []
let offsetMs: Promise<number> | null = null

async function mockFetch<T>(path: string): Promise<T> {
  const r = await fetch(`/mock/${path}.json`)
  // A missing public file comes back as the SPA's index.html with a 200.
  if (!r.ok || !r.headers.get('content-type')?.includes('json'))
    throw new Error(`mock fixture missing: ${path}`)
  return r.json() as Promise<T>
}

// ms to add to every fixture timestamp so `updated_at` lands just before now
function timeOffset(): Promise<number> {
  offsetMs ??= mockFetch<HouseState>('house').then(
    (h) => Date.now() - LAST_CHECK_AGO_MS - Date.parse(h.updated_at),
  )
  return offsetMs
}

function shift(iso: string, ms: number): string {
  return new Date(Date.parse(iso) + ms).toISOString()
}

function elapsedS(): number {
  return sim ? (Date.now() - sim.startedAt) / 1000 : 0
}

function scoreWord(score: number): ScoreWord {
  return score >= 75 ? 'Good' : score >= 60 ? 'Fair' : 'Attention'
}

function simSeverity(): Severity {
  return elapsedS() >= ALERT_AFTER_S ? 'alert' : 'watch'
}

function simLatest(l: SensorLatest): SensorLatest {
  if (l.rh_pct == null) return l
  const k = Math.min(1, elapsedS() / RH_RAMP_S)
  return { ...l, rh_pct: l.rh_pct + (LEAK_RH - l.rh_pct) * k }
}

function applySim(h: HouseState): HouseState {
  if (!sim) return { ...h, simulating: false }
  const severity = simSeverity()
  const score = Math.max(
    52,
    Math.round(h.score - (h.score - 52) * Math.min(1, elapsedS() / SCORE_DROP_S)),
  )
  const target = h.sensors.find((s) => s.id === sim!.targetId)
  const where = (target?.name ?? 'roof').toLowerCase()
  const attention: AttentionItem[] = [
    {
      sensor_id: sim.targetId,
      severity,
      message:
        severity === 'alert'
          ? `Moisture in the ${where} has risen sharply — this pattern usually means a leak. We recommend having it checked.`
          : `Moisture in the ${where} is rising slowly. We're watching it — no action needed yet.`,
      since: new Date(sim.startedAt).toISOString(),
      actions: severity === 'alert' ? ['inspection', 'expert'] : ['expert'],
    },
  ]
  const area = target?.zone === 'crawl_space' ? 'crawl_space' : 'roof'
  return {
    ...h,
    score,
    score_word: scoreWord(score),
    areas: h.areas.map((a) => (a.id === area ? { ...a, status: severity } : a)),
    score_factors: [
      {
        code: 'SENSOR_LEAK_SIMULATED',
        severity: 'attention',
        location: where,
        detail: { peak_rh: LEAK_RH, simulated: true },
      },
    ],
    score_trend: 'declining',
    headline:
      severity === 'alert' ? 'Possible leak in the roof' : 'One area needs watching',
    summary:
      severity === 'alert'
        ? 'We found a likely leak in the roof. Everything else looks normal.'
        : 'One area of the roof needs watching — the rest of the house looks normal.',
    recommendations:
      severity === 'alert'
        ? ['Have the roof checked — fixing a leak early keeps repairs small.']
        : ["Keep an eye on the roof — we'll tell you if it keeps rising."],
    narrative_source: 'demo',
    attention,
    sensors: h.sensors.map((s) =>
      s.id === sim!.targetId
        ? { ...s, status: severity, latest: simLatest(s.latest) }
        : s,
    ),
    simulating: true,
  }
}

export const mock: Api = {
  async getHouseState() {
    const [h, ms] = await Promise.all([mockFetch<HouseState>('house'), timeOffset()])
    const sensors: HouseSensor[] = h.sensors.map((s) => ({
      ...s,
      last_reading_at: shift(s.last_reading_at, ms),
    }))
    return applySim({
      ...h,
      sensors,
      open_requests: requests,
      updated_at: shift(h.updated_at, ms),
    })
  },

  async getSensor(id) {
    const [raw, ms] = await Promise.all([mockFetch<SensorDetail>(`sensors/${id}`), timeOffset()])
    const d = {
      ...raw,
      last_reading_at: shift(raw.last_reading_at, ms),
      updated_at: shift(raw.updated_at, ms),
    }
    if (!sim || id !== sim.targetId) return d
    const severity = simSeverity()
    return {
      ...d,
      status: severity,
      latest: simLatest(d.latest),
      status_text:
        severity === 'alert'
          ? 'Humidity has risen sharply here in the last hour — this pattern usually means a new leak.'
          : "Humidity here is rising slowly. We're watching it — no action needed yet.",
    }
  },

  async getSeries(id, range) {
    const [raw, ms] = await Promise.all([
      mockFetch<SensorSeries>(`series/${id}-${range}`),
      timeOffset(),
    ])
    const s = { ...raw, points: raw.points.map((p) => ({ ...p, t: shift(p.t, ms) })) }
    if (!sim || id !== sim.targetId || range !== '24h') return s
    // Ramp the tail of the 24 h series so the fresh leak is visible.
    const t = Math.min(1, elapsedS() / RH_RAMP_S)
    const n = Math.min(24, s.points.length)
    const points = s.points.map((p, i) => {
      const k = (i - (s.points.length - n)) / n
      if (k < 0 || p.rh_pct == null) return p
      return { ...p, rh_pct: p.rh_pct + (LEAK_RH - p.rh_pct) * t * k }
    })
    return { ...s, points }
  },

  async simulateLeak(sensorId) {
    sim = { startedAt: Date.now(), targetId: sensorId ?? LEAK_TARGET_DEFAULT }
  },

  async resetDemo() {
    sim = null
    requests = []
  },

  async requestHelp(kind, sensorId) {
    if (!requests.some((r) => r.kind === kind))
      requests = [
        ...requests,
        {
          kind,
          sensor_id: sensorId ?? null,
          requested_at: new Date().toISOString(),
          status_text: HELP_STATUS[kind],
        },
      ]
    return { message: HELP_CONFIRMATION[kind] }
  },

  getReport() {
    return mockFetch<Report>('report')
  },
}
