// Mock API — reads static fixtures from /mock/*.json (generated by
// scripts/gen_mock_data.py) and overlays an in-memory leak simulation so the
// whole demo flow works without a backend.
import type {
  Api,
  AttentionItem,
  HouseState,
  ScoreWord,
  SensorDetail,
  SensorLatest,
  SensorSeries,
  Severity,
} from './types'

const LEAK_TARGET_DEFAULT = 'roof-nw' // north slope — where moisture collects
const ALERT_AFTER_S = 45 // watch -> alert transition
const SCORE_DROP_S = 150 // score falls to 52 over this span
const RH_RAMP_S = 240 // leak humidity climbs to LEAK_RH over this span
const LEAK_RH = 92

let sim: { startedAt: number; targetId: string } | null = null

async function mockFetch<T>(path: string): Promise<T> {
  const r = await fetch(`/mock/${path}.json`)
  // A missing public file comes back as the SPA's index.html with a 200.
  if (!r.ok || !r.headers.get('content-type')?.includes('json'))
    throw new Error(`mock fixture missing: ${path}`)
  return r.json() as Promise<T>
}

function elapsedS(): number {
  return sim ? (Date.now() - sim.startedAt) / 1000 : 0
}

function scoreWord(score: number): ScoreWord {
  return score >= 75 ? 'Good' : score >= 60 ? 'Fair' : 'Attention'
}

function simSeverity(): Severity {
  return elapsedS() >= ALERT_AFTER_S ? 'alert' : 'watch'
}

function simLatest(l: SensorLatest): SensorLatest {
  if (l.rh_pct == null) return l
  const k = Math.min(1, elapsedS() / RH_RAMP_S)
  return { ...l, rh_pct: l.rh_pct + (LEAK_RH - l.rh_pct) * k }
}

function applySim(h: HouseState): HouseState {
  if (!sim) return { ...h, simulating: false }
  const severity = simSeverity()
  const score = Math.max(
    52,
    Math.round(h.score - (h.score - 52) * Math.min(1, elapsedS() / SCORE_DROP_S)),
  )
  const target = h.sensors.find((s) => s.id === sim!.targetId)
  const where = (target?.name ?? 'roof').toLowerCase()
  const attention: AttentionItem[] = [
    {
      sensor_id: sim.targetId,
      severity,
      message:
        severity === 'alert'
          ? `Moisture in the ${where} has risen sharply — this pattern usually means a leak. We've flagged it for review.`
          : `Moisture in the ${where} is rising slowly. We're watching it — no action needed yet.`,
      since: new Date(sim.startedAt).toISOString(),
    },
  ]
  return {
    ...h,
    score,
    score_word: scoreWord(score),
    score_trend: 'declining',
    headline:
      severity === 'alert' ? 'Possible leak in the roof' : 'One area needs watching',
    summary:
      severity === 'alert'
        ? 'We found a likely leak in the roof. Everything else looks normal.'
        : 'One area of the roof needs watching — the rest of the house looks normal.',
    attention,
    sensors: h.sensors.map((s) =>
      s.id === sim!.targetId
        ? { ...s, status: severity, latest: simLatest(s.latest) }
        : s,
    ),
    simulating: true,
  }
}

export const mock: Api = {
  async getHouseState() {
    return applySim(await mockFetch<HouseState>('house'))
  },

  async getSensor(id) {
    const d = await mockFetch<SensorDetail>(`sensors/${id}`)
    if (!sim || id !== sim.targetId) return d
    const severity = simSeverity()
    return {
      ...d,
      status: severity,
      latest: simLatest(d.latest),
      status_text:
        severity === 'alert'
          ? 'Humidity has risen sharply here in the last hour — this pattern usually means a new leak.'
          : "Humidity here is rising slowly. We're watching it — no action needed yet.",
    }
  },

  async getSeries(id, range) {
    const s = await mockFetch<SensorSeries>(`series/${id}-${range}`)
    if (!sim || id !== sim.targetId || range !== '24h') return s
    // Ramp the tail of the 24 h series so the fresh leak is visible.
    const t = Math.min(1, elapsedS() / RH_RAMP_S)
    const n = Math.min(24, s.points.length)
    const points = s.points.map((p, i) => {
      const k = (i - (s.points.length - n)) / n
      if (k < 0 || p.rh_pct == null) return p
      return { ...p, rh_pct: p.rh_pct + (LEAK_RH - p.rh_pct) * t * k }
    })
    return { ...s, points }
  },

  async simulateLeak(sensorId) {
    sim = { startedAt: Date.now(), targetId: sensorId ?? LEAK_TARGET_DEFAULT }
  },

  async resetDemo() {
    sim = null
  },
}
